<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class ExcerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('excercises')->insert([
            [
            /** Chest */
                'name' => 'Dumbbell Bench Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/dumbbell-bench-press_0.jpg',
                'description' => 'The dumbbell bench press is a strength exercise primarily targeting the chest, shoulders, and triceps. Performed while lying on a bench, it involves pressing dumbbells upward from chest level until the arms are fully extended. This exercise helps build upper body strength, enhances muscle coordination, and improves overall chest definition.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Chest',
            ],
            [
                'name' => 'Hammer Strength Bench Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/machine-bench-press_0.jpg',
                'description' => 'The Hammer Strength Bench Press is a machine-based exercise designed to target the chest, shoulders, and triceps. It offers guided, controlled motion for pressing weights upward from chest level, enhancing safety and stability. This exercise is ideal for building upper body strength and muscle definition with reduced injury risk.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Chest',
            ],
            [
                'name' => 'Standing Cable Fly',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/standing-cable-fly1.jpg',
                'description' => 'The standing cable fly is an exercise targeting the chest muscles. Performed with cables at chest height, it involves pulling the handles together in front of the body, maintaining slight elbow bends. This movement enhances chest muscle definition, improves upper body strength, and engages the shoulders and stabiliser muscles.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Cable',
                'main_muscles_targeted' => 'Chest',
            ],
            [
                'name' => 'Decline Dumbbell Bench Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/decline-dumbbell-bench-press.jpg',
                'description' => 'The decline dumbbell bench press targets the lower chest muscles. Performed on a decline bench, it involves pressing dumbbells upward from a lower chest position. This exercise enhances lower chest definition, improves overall upper body strength, and engages the shoulders and triceps for a balanced muscle development.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Chest',
            ],

            [
                'name' => 'Decline Smith Machine Bench Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/smith-machine-decline-bench-press.jpg',
                'description' => 'The decline Smith machine bench press targets the lower chest by performing the exercise on a decline bench. The Smith machine stabilises the barbell, allowing for a controlled range of motion. This variation enhances muscle activation in the lower pectorals and can aid in developing a balanced chest.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Chest',
            ],

            [
                'name' => 'Push Ups',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/push-ups.jpg',
                'description' => 'Push-ups are a bodyweight exercise that strengthens the chest, shoulders, and triceps. By lowering your body towards the ground and then pressing up, you engage your chest muscles. This exercise can be modified for different fitness levels, enhancing muscle tone and endurance while requiring minimal equipment.',
                'rating' => 3,
                'level' => 'Beginner',
                'equipment_type' => 'Bodyweight',
                'main_muscles_targeted' => 'Chest',
            ],
            
            [
                'name' => 'Dumbbell Pullover',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/dumbbell-pullover.jpg',
                'description' => 'Dumbbell pullovers are an effective exercise for targeting the chest and lats. Lying on a bench, you extend a dumbbell from above your chest to behind your head, then return to the starting position. This movement enhances upper body strength and flexibility, promoting overall muscular development.',
                'rating' => 2,
                'level' => 'Intermediate',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Chest',
            ],
            [
                'name' => 'Alternating Dumbbell Bench Press on Exercise Ball',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/alternating-dumbbell-bench-press-on-exercise-ball.jpg',
                'description' => 'The decline dumbbell bench press targets the lower chest muscles. Performed on a decline bench, it involves pressing dumbbells upward from a lower chest position. This exercise enhances lower chest definition, improves overall upper body strength, and engages the shoulders and triceps for a balanced muscle development.',
                'rating' => 1,
                'level' => 'Intermediate',
                'equipment_type' => 'Excercise ball & Dumbbell',
                'main_muscles_targeted' => 'Chest',
            ],
            /** Back */
            [
                'name' => 'Machine T-Bar Row',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/machine-t-bar-row.jpg',
                'description' => 'The machine T-bar row focuses on strengthening the back muscles, particularly the lats and rhomboids. By pulling a weighted bar towards your chest while seated, you engage your upper and middle back. This exercise provides stability and control, helping to build a well-defined and powerful back.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Back',
            ],
            [
                'name' => 'Seated Cable Row',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/seated-cable-row.jpg?itok=b8Yzo0KK',
                'description' => 'The seated cable row targets the upper and middle back muscles, including the lats and rhomboids. Seated with feet braced, you pull the cable handle towards your torso, squeezing the shoulder blades together. This controlled movement enhances back strength, improves posture, and promotes muscular development.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Cable',
                'main_muscles_targeted' => 'Back',
            ],
            [
                'name' => 'Bent Over Row',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/bent-over-row.jpg',
                'description' => 'The bent-over row is a compound exercise that builds back strength, focusing on the lats, rhomboids, and rear delts. Bent at the waist with a barbell or dumbbells, you pull the weight towards your torso while keeping your back straight. This movement improves posture and enhances overall back development.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Barbell',
                'main_muscles_targeted' => 'Back',
            ],
            [
                'name' => 'Wide Grip Chin Up',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/wide-grip-chin-up.jpg?itok=5DVIkY6Y',
                'description' => 'The wide-grip chin-up is an advanced bodyweight exercise targeting the upper back and biceps. By gripping the bar wider than shoulder-width, you emphasise the lats and outer back. Pulling your body up until your chin surpasses the bar enhances strength, muscle definition, and overall upper body power.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Bodyweight',
                'main_muscles_targeted' => 'Back',
            ],
            [
                'name' => 'Deadlift',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/deadlift_0.jpg',
                'description' => 'Deadlifts are a full-body exercise that primarily targets the posterior chain, including the hamstrings, glutes, and lower back. By lifting a barbell from the ground to hip level with proper form, you engage multiple muscle groups. This compound movement improves strength, posture, and overall functional fitness.',
                'rating' => 3,
                'level' => 'Intermediate',
                'equipment_type' => 'Barbell',
                'main_muscles_targeted' => 'Back',
            ],
            [
                'name' => 'Deadstop Rack Row',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/deadstop-rack-row.jpg',
                'description' => 'The deadstop rack row is a strength-building exercise targeting the upper back and lats. Performed with the barbell set on a rack, you pull the bar towards your torso from a dead stop, ensuring full muscle engagement and minimising momentum. This controlled movement improves back strength and muscular development.',
                'rating' => 2,
                'level' => 'Beginner',
                'equipment_type' => 'Barbell',
                'main_muscles_targeted' => 'Back',
            ],
            [
                'name' => 'Reverse Grip Bent-Over Row (EZ Bar)',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/reverse-grip-bent-over-row-ez-bar.jpg?itok=_MwQ6G_p',
                'description' => 'The wide-grip chin-up is an advanced bodyweight exercise targeting the upper back and biceps. By gripping the bar wider than shoulder-width, you emphasise the lats and outer back. Pulling your body up until your chin surpasses the bar enhances strength, muscle definition, and overall upper body power.',
                'rating' => 1,
                'level' => 'Beginner',
                'equipment_type' => 'EZ Bar',
                'main_muscles_targeted' => 'Back',
            ],
            [
                'name' => 'Renegade Rows',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/renegade-row.jpg',
                'description' => 'The reverse grip bent-over row with an EZ bar targets the upper back, lats, and biceps. Bent at the waist, you pull the EZ bar towards your lower chest using an underhand grip. This variation emphasises different muscle angles, enhancing back strength, muscle definition, and overall stability.',
                'rating' => 1,
                'level' => 'Intermediate',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Back',
            ],
            /** Shoulder */
            [
                'name' => 'Machine Shoulder Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/machine-shoulder-press.jpg',
                'description' => 'The machine shoulder press isolates the deltoid muscles by providing a stable, controlled movement. Seated with adjustable arms, you push the handles upward to extend your arms, then lower back to the starting position. This exercise enhances shoulder strength, muscle definition, and promotes balanced upper body development.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Shoulders',
            ],
            [
                'name' => 'Seated Dumbbell Lateral Raise',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/seated-dumbbell-lateral-raise.jpg?itok=i7jPp1X4',
                'description' => 'The seated dumbbell lateral raise isolates the shoulder muscles, especially the deltoids. While seated, hold dumbbells at your sides and lift them outward to shoulder height, then lower them slowly. This controlled movement enhances shoulder strength, definition, and stability, promoting balanced upper body development.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Shoulders',
            ],
            [
                'name' => 'Single Arm Cable Lateral Raise (Crossbody)',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/single-arm-cable-lateral-raise.jpg',
                'description' => 'The single-arm cable lateral raise (crossbody) targets the deltoids by isolating each shoulder individually. Standing with the cable set low, pull the handle across your body and raise it to shoulder height, then lower it slowly. This exercise enhances shoulder strength, stability, and muscle definition with a controlled range of motion.',
                'rating' => 4,
                'level' => 'Intermediate',
                'equipment_type' => 'Cable',
                'main_muscles_targeted' => 'Shoulders',
            ],
            [
                'name' => 'Machine Reverse Fly',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/machine-reverse-fly.jpg',
                'description' => 'The machine reverse fly focuses on the rear deltoids and upper back. Seated with chest against the pad, you pull the handles outward, squeezing your shoulder blades together, then return slowly. This controlled movement enhances shoulder stability, muscle definition, and overall upper back strength.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Shoulders',
            ],
            [
                'name' => 'Smith Machine Shoulder Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/seated-military-press.jpg',
                'description' => 'The Smith machine shoulder press targets the deltoid muscles with added stability. Seated with the barbell set on the Smith machine, press the weight overhead from shoulder height, then lower it back down. This exercise enhances shoulder strength, muscle definition, and offers controlled, consistent movement for safer lifting.',
                'rating' => 3,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Shoulders',
            ],
            [
                'name' => 'Seated Arnold Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/seated-arnold-press-thumb.jpg',
                'description' => 'The seated Arnold press targets the shoulders and engages the deltoids from multiple angles. Start with dumbbells in front of you, palms facing, and rotate them as you press upward. This movement enhances shoulder strength, muscle definition, and promotes balanced upper body development through its unique motion.',
                'rating' => 2,
                'level' => 'Intermediate',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Shoulders',
            ],
            [
                'name' => 'Bus Drivers',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/bus-drivers.jpg',
                'description' => 'Bus drivers, or "bus driver" shoulder raises, target the deltoids and traps. Holding a weight plate or dumbbell at chest level, you rotate it as if steering a bus, raising and lowering the weight in a circular motion. This exercise improves shoulder strength, stability, and overall upper body conditioning.',
                'rating' => 1,
                'level' => 'Beginner',
                'equipment_type' => 'Weighted Plate',
                'main_muscles_targeted' => 'Shoulders',
            ],
            [
                'name' => 'Weighted Plate Front Raise',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/weight-plate-front-raise.jpg?itok=mEj6P2uw',
                'description' => 'The weighted plate front raise targets the front deltoids and upper traps. Holding a weight plate with both hands, you lift it straight in front of you to shoulder height, then lower it back down. This exercise enhances shoulder strength, muscle definition, and overall upper body stability.',
                'rating' => 1,
                'level' => 'Beginner',
                'equipment_type' => 'Weighted Plate',
                'main_muscles_targeted' => 'Shoulders',
            ],
            /** Legs */
            [
                'name' => 'Leg Press',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/leg-press.jpg',
                'description' => 'The leg press is a lower body exercise targeting the quads, hamstrings, and glutes. Seated with feet on a platform, you push the weight away by extending your legs, then return to the starting position. This machine-based exercise enhances leg strength, muscle definition, and overall lower body power.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Legs',
            ],
            [
                'name' => 'Hack Squat',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/machine-hack-squat-1.jpg',
                'description' => 'The hack squat targets the quads, hamstrings, and glutes. Positioned on a machine with your back against the pad, you lower your body by bending your knees, then push up to the starting position. This exercise enhances leg strength, muscle definition, and overall lower body development through controlled movement.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Legs',
            ],
            [
                'name' => 'Leg Extension',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/leg-extension.jpg',
                'description' => 'The leg extension isolates the quadriceps, enhancing muscle strength and definition. Seated with legs under a padded bar, extend your knees to lift the weight, then lower slowly. This exercise targets the front of the thighs, improving leg strength and contributing to overall lower body conditioning.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Legs',
            ],
            [
                'name' => 'Single Leg Extension',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/single-leg-extension_0.jpg',
                'description' => 'The single leg extension isolates each quadricep individually. Seated with one leg positioned under the padded bar, extend the leg upward while keeping the other leg stationary, then lower it slowly. This exercise enhances quad strength, muscle balance, and definition by focusing on one leg at a time.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Legs',
            ],
            [
                'name' => 'Sumo Deadlift',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/sumo-deadlift-1.jpg',
                'description' => 'The sumo deadlift targets the inner thighs, glutes, and lower back. With a wide stance and feet turned out, you lift a barbell from the ground by extending your hips and knees, then lower it back down. This variation emphasizes different muscle groups, enhancing strength and flexibility.',
                'rating' => 3,
                'level' => 'Beginner',
                'equipment_type' => 'Barbell',
                'main_muscles_targeted' => 'Legs',
            ],
            [
                'name' => 'Dumbbell Goblet Squat',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/dumbbell-goblet-squat-1.jpg',
                'description' => 'The dumbbell goblet squat is a versatile lower body exercise that targets the quads, glutes, and hamstrings. Holding a dumbbell close to your chest, squat down with feet shoulder-width apart, then push back up to standing. This movement enhances leg strength, core stability, and overall lower body development.',
                'rating' => 2,
                'level' => 'Beginner',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Legs',
            ],
            [
                'name' => 'Dumbbell Hamstring Curl',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/dumbbell-hamstring-curl.jpg?itok=XswiLk_G',
                'description' => 'The dumbbell hamstring curl isolates and strengthens the hamstrings. Lying face down on a bench, hold a dumbbell between your feet, curl it upwards towards your glutes, then lower it slowly. This exercise enhances hamstring strength, muscle definition, and supports balanced lower body development.',
                'rating' => 1,
                'level' => 'Intermediate',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Legs',
            ],
            [
                'name' => 'Bodyweight Single Leg Deadlift',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/bodyweight-single-leg-deadlift.jpg',
                'description' => 'The bodyweight single-leg deadlift targets the hamstrings, glutes, and core. Balancing on one leg, hinge at the hips while extending the free leg behind you, then return to standing. This exercise enhances balance, strength, and flexibility while improving overall lower body stability.',
                'rating' => 1,
                'level' => 'Intermediate',
                'equipment_type' => 'Bodyweight',
                'main_muscles_targeted' => 'Legs',
            ],
            /** Arms */
            [
                'name' => 'Standing Dumbbell Curl',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/standing-dumbbell-curl.jpg?itok=Kj5-H30y',
                'description' => 'Standing dumbbell curls target the biceps by isolating the upper arms. With arms fully extended and palms facing forward, curl the dumbbells up towards your shoulders, then lower them slowly. This exercise enhances bicep strength, muscle definition, and overall arm development through a controlled motion.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Arms',
            ],
            [
                'name' => 'EZ Bar Skullcrusher',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/ez-bar-skullcrusher_0.jpg',
                'description' => 'The EZ bar skull crusher targets the triceps with a focus on the long head. Lying on a bench, hold the EZ bar with an overhand grip and lower it towards your forehead, then extend your arms back to the starting position. This exercise enhances tricep strength, muscle definition, and overall arm development.',
                'rating' => 5,
                'level' => 'Beginner',
                'equipment_type' => 'EZ Bar',
                'main_muscles_targeted' => 'Arms',
            ],
            [
                'name' => 'Standing Bar Tricep Extension',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/straight-bar-tricep-extension-1.jpg',
                'description' => 'The straight bar tricep extension focuses on the triceps. Using an overhand grip, hold a barbell overhead, then lower it behind your head before extending back up. This exercise isolates the triceps, enhancing muscle strength and definition while improving overall arm development and stability.',
                'rating' => 4,
                'level' => 'Beginner',
                'equipment_type' => 'Cable',
                'main_muscles_targeted' => 'Arms',
            ],
            [
                'name' => 'Cable Curl',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/cable-curl.jpg?itok=dGZkncUa',
                'description' => 'Cable curls effectively target the biceps by maintaining constant tension throughout the movement. Standing or seated, grasp the cable handle with an underhand grip, curl it towards your shoulders, and then lower it slowly. This exercise enhances bicep strength, muscle definition, and improves overall arm development.',
                'rating' => 3,
                'level' => 'Beginner',
                'equipment_type' => 'Cable',
                'main_muscles_targeted' => 'Arms',
            ],
            [
                'name' => 'Machine Tricep Extension',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/machine-tricep-extension.jpg',
                'description' => 'The machine tricep extension isolates and strengthens the triceps. Seated at the machine, adjust the weight and grip the handles, then extend your arms downward while keeping your elbows stationary. This controlled movement enhances tricep muscle definition and overall arm strength with consistent resistance.',
                'rating' => 2,
                'level' => 'Beginner',
                'equipment_type' => 'Machine',
                'main_muscles_targeted' => 'Arms',
            ],
            [
                'name' => 'Bench Dip',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/bench-dip.jpg?itok=x4U98F1X',
                'description' => 'Bench dips target the triceps, shoulders, and chest. Seated on a bench with hands beside your hips, slide forward and lower your body by bending your elbows, then press back up. This bodyweight exercise enhances arm strength, muscle definition, and upper body endurance.',
                'rating' => 2,
                'level' => 'Beginner',
                'equipment_type' => 'BodyWeight',
                'main_muscles_targeted' => 'Arms',
            ],
            [
                'name' => 'Dumbbell Tricep Kickback',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/dumbbell-tricep-kickback.jpg?itok=Lj4skmNj',
                'description' => 'The dumbbell tricep kickback isolates the triceps for effective muscle building. Bent over with one knee on a bench, hold a dumbbell in one hand, extend your arm straight back, then return to the starting position. This movement enhances tricep strength, muscle definition, and arm stability.',
                'rating' => 1,
                'level' => 'Beginner',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Arms',
            ],
            [
                'name' => 'Lying Dumbbell Curl',
                'image' => 'https://cdn.muscleandstrength.com/sites/default/files/styles/800x500/public/lying-dumbbell-curl.jpg?itok=2lZFPVtR',
                'description' => 'The lying dumbbell curl targets the biceps by minimizing shoulder involvement. Lying on a bench with arms extended down, curl the dumbbells towards your shoulders, then lower them slowly. This exercise isolates the biceps, enhancing strength and muscle definition while reducing momentum for a more focused contraction.',
                'rating' => 1,
                'level' => 'Intermediate',
                'equipment_type' => 'Dumbbell',
                'main_muscles_targeted' => 'Arms',
            ],
        ]);
    }
}
